pull_request_rules:
  - name: Automatic merge
    conditions:
      - or:
          - 'author=dependabot[bot]'
          - 'label=wait-merge'
      - -draft
      - -merged
      - -closed
      - check-success=check
    actions:
      queue:
        name: default
  - name: Handle merged
    conditions:
      - 'label=wait-merge'
      - or:
          - merged
          - closed
    actions:
      label:
        remove: ["wait-merge"]
queue_rules:
  - name: default
    merge_method: squash
    merge_conditions:
      - check-success=check
