name: Heartbeat

on:
  pull_request:
    types:
      - closed

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}
    steps:
      - name: Heartbeat
        run: |
          curl -f -s "https://uptime.betterstack.com/api/v1/heartbeat/${{ secrets.HEARTBEAT_KEY }}"
