name: Tidy

on:
  - workflow_dispatch
  - push

permissions:
  contents: write

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Exclude
        run: scripts/exclude.sh

      - name: Generate
        run: scripts/generate.sh

      - name: Tidy
        run: |
          go mod tidy

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          if git diff --quiet HEAD; then
            echo "No changes"
            exit 0
          fi
          git commit -m 'chore: auto tidy'
          git push
