name: Tidy

on: workflow_dispatch

permissions:
  contents: write

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Exclude
        run: |
          while read -r MODULE; do
            if ! go get "$MODULE@latest"; then
              echo "$MODULE" >> exclude.txt
            fi
          done < list.txt
          grep -F -v -f exclude.txt list.txt > list.txt.tmp
          mv list.txt.tmp list.txt
          make generate

      - name: Tidy
        run: |
          go mod tidy

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Tidy go.mod and go.sum'
          git push
